export EDITOR=vim
export HISTFILESIZE=$HISTSIZE
export HISTIGNORE=[fb]g
export HISTSIZE=100000
export PAGER="less -R"

alias be="bundle exec"
alias c="curl"
alias cl="clear"
alias con="cd ~deploy/thneed/current; bundle exec rails console"
alias db="~deploy/thneed/current/bin/sqlite3 ~/thneed/shared/storage/primary.sqlite3"
alias e="exa"
alias et="exa -snew"
alias fd="fdfind"
alias gerp="grep"
alias g="git"
alias log="cd ~deploy/thneed/shared/log"
alias s="~deploy/thneed/current/bin/sqlite3"
alias sqlite3="~deploy/thneed/current/bin/sqlite3"
alias vi="vim"

set -o vi
