#!/bin/bash

# The full-page cache uses Tempfile to write to a .(random) filename and rename
# to the final. At the tail of a deploy, this script could delete the file
# between those two steps and the rename would throws an exception. Catching
# that might mask real bugs filling the cache, so we don't delete those
# tempfiles. Leaving a handful of cached files is OK.
find /home/deploy/thneed/current/public/cache/ -name s -type d -prune -o -type f -not -name '.*' -exec rm -f -- {} +

# kick off rebuilding story page cache
cd /home/deploy/thneed/current
bundle exec rails runner "RefillStoryPageCacheJob.perform_later"

# see hatchbox/root-deploy
touch /home/deploy/thneed/current
